### ISSUE TITLE
报错应该是gluonts版本问题

### ISSUE THREAD

**Issue by endlessfireable** [kongqi404/timegrad#1]
感谢作者的注释，看到你的报错应该是版本问题，将gluonts版本改成gluonts=10.0.0.0即可，不知道作者是否还在进行timegrad的源码研究，不知道是否能共同交流

**Comment by kongqi404** [comment]
对的，但是我本来是准备迁移到latest版本的gluonts或者用纯pytorch重写下timegrad，现在只完成了概率输出的重写，diffusion的重写还没进行

**Comment by endlessfireable** [comment]
想请问下纯pytorch的部分概率重写是可以开源的吗，gluonts封装的我晕了，我想魔改一下这个模型做时序相关的其他工作，不知道您的代码可以开源吗


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日 18:44:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongqi404/timegrad] 报错应该是gluonts版本问题 (Issue #1)




 
对的，但是我本来是准备迁移到latest版本的gluonts或者用纯pytorch重写下timegrad，现在只完成了概率输出的重写，diffusion的重写还没进行

**Comment by kongqi404** [comment]
可以，等我整理下就可以开源，实现很简单

endlessfireable ***@***.***> 于 2023年3月17日周五 19:05写道：

**Comment by kongqi404** [comment]
> 想请问下纯pytorch的部分概率重写是可以开源的吗，gluonts封装的我晕了，我想魔改一下这个模型做时序相关的其他工作，不知道您的代码可以开源吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月16日 18:44:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [kongqi404/timegrad] 报错应该是gluonts版本问题 (Issue #1) 对的，但是我本来是准备迁移到latest版本的gluonts或者用纯pytorch重写下timegrad，现在只完成了概率输出的重写，diffusion的重写还没进行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

here is prob forecasting code:https://gist.github.com/kongqi404/336a8031901a3cebc05585b78fa650ef
